FROM python:3.8-slim as base

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir rasa==3.6.10

WORKDIR /nika/problem-solver/cxx/messageClassificationModule/rasa_classifier_model

COPY ./models ./models
COPY ./components ./components
COPY ./data ./data

EXPOSE 5005

CMD ["rasa", "run", "--enable-api", "-m", "models/"]